import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { siteData } from "@/config/site-data";
import PromoBar from "@/components/ui/PromoBar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    name: siteData.general.brandName,
    url: typeof window !== "undefined" ? window.location.origin : "",
    telephone: siteData.general.whatsappNumbers[0],
    description: "Your trusted marketplace for quality products.",
  };

  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-sans`}
      >
        <PromoBar />
        {children}
        {siteData.features.enableSEOJSONLD && (
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
          />
        )}
      </body>
    </html>
  );
}
