export const siteData = {
    features: {
        enableFloatingWA: true,
        waRotator: true,
        enableAnimations: true,
        enableSEOJSONLD: true,
        enablePromoBar: false,
    },
    general: {
        brandName: "PropNest",
        tagline: "Find Your Dream Property",
        whatsappNumbers: [
            "6281234567890",
            "6289876543210",
        ],
        whatsappMessage: "Halo, saya tertarik dengan properti yang ditampilkan. Mohon info lebih lanjut.",
        email: "info@propnest.id",
        phone: "+62 21 1234 5678",
        address: "Jl. Sudirman No. 123, Jakarta Selatan",
    },
    social: {
        facebook: "https://facebook.com/propnest",
        instagram: "https://instagram.com/propnest",
        twitter: "https://twitter.com/propnest",
        youtube: "https://youtube.com/@propnest",
        linkedin: "https://linkedin.com/company/propnest",
    },
    navbar: {
        links: [
            { label: "Beranda", href: "/" },
            { label: "Properti", href: "/properties" },
            { label: "Tentang Kami", href: "#about" },
            { label: "Kontak", href: "#contact" },
        ],
    },
    hero: {
        headline: "Temukan Hunian Impian Anda",
        subheadline: "Koleksi properti premium terbaik di lokasi strategis dengan harga kompetitif",
        backgroundImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=2000&auto=format&fit=crop",
    },
    promoBar: {
        message: "🏠 Promo Spesial: Konsultasi GRATIS untuk pembelian properti pertama Anda!",
        linkText: "Hubungi Kami",
        linkUrl: "#contact",
        backgroundColor: "bg-gold-500",
    },
    stats: [
        { value: "500+", label: "Properti Tersedia" },
        { value: "1,200+", label: "Klien Puas" },
        { value: "50+", label: "Agen Profesional" },
        { value: "15+", label: "Tahun Pengalaman" },
    ],
    propertyTypes: [
        { icon: "Home", label: "Rumah", slug: "rumah", count: 156 },
        { icon: "Building2", label: "Apartemen", slug: "apartemen", count: 89 },
        { icon: "Castle", label: "Villa", slug: "villa", count: 34 },
        { icon: "Landmark", label: "Tanah", slug: "tanah", count: 67 },
        { icon: "Building", label: "Ruko", slug: "ruko", count: 45 },
        { icon: "Warehouse", label: "Gudang", slug: "gudang", count: 23 },
    ],
    whyChooseUs: [
        {
            icon: "Shield",
            title: "Terpercaya",
            description: "Lebih dari 15 tahun pengalaman dalam industri properti Indonesia",
        },
        {
            icon: "BadgeCheck",
            title: "Legalitas Jelas",
            description: "Semua properti telah diverifikasi dengan dokumen lengkap dan sah",
        },
        {
            icon: "Headphones",
            title: "Konsultasi Gratis",
            description: "Tim ahli siap membantu Anda menemukan properti yang tepat",
        },
        {
            icon: "Wallet",
            title: "Harga Terbaik",
            description: "Negosiasi langsung dengan pemilik untuk harga paling kompetitif",
        },
    ],
    featuredProperties: [
        {
            id: "1",
            title: "Modern Minimalist House",
            location: "BSD City, Tangerang Selatan",
            price: 2500000000,
            type: "rumah",
            bedrooms: 4,
            bathrooms: 3,
            area: 180,
            image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1000&auto=format&fit=crop",
            badge: "Best Seller",
            isNew: false,
        },
        {
            id: "2",
            title: "Luxury Apartment Sudirman",
            location: "SCBD, Jakarta Selatan",
            price: 3800000000,
            type: "apartemen",
            bedrooms: 3,
            bathrooms: 2,
            area: 145,
            image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1000&auto=format&fit=crop",
            badge: "Premium",
            isNew: true,
        },
        {
            id: "3",
            title: "Villa Bali Style",
            location: "Canggu, Bali",
            price: 5500000000,
            type: "villa",
            bedrooms: 5,
            bathrooms: 4,
            area: 350,
            image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1000&auto=format&fit=crop",
            badge: "Exclusive",
            isNew: false,
        },
        {
            id: "4",
            title: "Strategic Land Plot",
            location: "Sentul, Bogor",
            price: 1200000000,
            type: "tanah",
            bedrooms: 0,
            bathrooms: 0,
            area: 500,
            image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000&auto=format&fit=crop",
            badge: "Investment",
            isNew: true,
        },
        {
            id: "5",
            title: "Townhouse Cluster Exclusive",
            location: "PIK 2, Jakarta Utara",
            price: 4200000000,
            type: "rumah",
            bedrooms: 4,
            bathrooms: 4,
            area: 220,
            image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
            badge: "New Launch",
            isNew: true,
        },
        {
            id: "6",
            title: "Commercial Shophouse",
            location: "Kelapa Gading, Jakarta Utara",
            price: 8500000000,
            type: "ruko",
            bedrooms: 0,
            bathrooms: 2,
            area: 280,
            image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1000&auto=format&fit=crop",
            badge: "Prime Location",
            isNew: false,
        },
    ],
    agents: [
        {
            id: "1",
            name: "Sarah Wijaya",
            title: "Senior Property Consultant",
            photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop",
            phone: "6281234567890",
            listings: 45,
            rating: 4.9,
        },
        {
            id: "2",
            name: "Michael Santoso",
            title: "Luxury Property Specialist",
            photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=400&auto=format&fit=crop",
            phone: "6289876543210",
            listings: 38,
            rating: 4.8,
        },
        {
            id: "3",
            name: "Amanda Chen",
            title: "Commercial Property Expert",
            photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=400&auto=format&fit=crop",
            phone: "6281122334455",
            listings: 52,
            rating: 5.0,
        },
    ],
    testimonials: [
        {
            name: "Budi Hartono",
            role: "Business Owner",
            photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
            review: "PropNest membantu saya menemukan ruko strategis untuk bisnis. Prosesnya cepat dan profesional!",
            rating: 5,
        },
        {
            name: "Linda Kusuma",
            role: "Software Engineer",
            photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop",
            review: "Apartemen impian saya di SCBD berhasil didapat dengan harga yang sangat kompetitif. Terima kasih PropNest!",
            rating: 5,
        },
        {
            name: "Hendro Prakoso",
            role: "Investor",
            photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
            review: "Sudah beberapa kali investasi properti melalui PropNest. Tim nya sangat membantu dalam analisa ROI.",
            rating: 5,
        },
    ],
    cta: {
        headline: "Siap Menemukan Properti Impian Anda?",
        subheadline: "Konsultasikan kebutuhan Anda dengan tim ahli kami secara gratis",
        buttonText: "Hubungi Kami Sekarang",
    },
    footer: {
        description: "PropNest adalah platform properti terpercaya yang menghubungkan Anda dengan hunian impian. Didukung oleh tim profesional dengan pengalaman lebih dari 15 tahun.",
        quickLinks: [
            { label: "Tentang Kami", href: "#about" },
            { label: "Karir", href: "#" },
            { label: "Syarat & Ketentuan", href: "#" },
            { label: "Kebijakan Privasi", href: "#" },
        ],
    },
};
